Bug 62861
ubikloadpack/jmeter pull request #46
Opened 2019-05-31 12:00 UTC by shaqianqian

## Description
Add a button in thread group to control the clear of cache and cookies

## Motivation and Context
To simplify the control of clearing caches and cookies

## How Has This Been Tested?
No

2019-06-02 17:14 UTC, ubikloadpack requested changes

2019-06-02 17:14 UTC, ubikloadpack commented on test/src/org/apache/jmeter/control/TestThreadGroup.java
> +    public void testThreadLoaclForSameUserOnIternation() {
Typo in name

2019-06-02 17:14 UTC, ubikloadpack commented on src/core/org/apache/jmeter/threads/ThreadGroup.java
> +    public static final String ISSAMEUSER = "ThreadGroup.sameuser";
Rename to IS_SAME_USER

2019-06-02 17:14 UTC, ubikloadpack commented on src/core/org/apache/jmeter/threads/ThreadGroup.java
> +    public boolean IsSameUser() {
functions must start with lower case

2019-06-02 17:14 UTC, ubikloadpack commented on src/core/org/apache/jmeter/threads/gui/ThreadGroupGui.java
> +       sameUserBox = new JRadioButton("Same user on each iteration"); //$NON-NLS-1$
Externalize labels into resource

2019-06-02 17:14 UTC, ubikloadpack commented on src/core/org/apache/jmeter/threads/gui/ThreadGroupGui.java
> +       differentUserBox = new JRadioButton("Different User on Each Iteration"); //$NON-NLS-1$
Externalize labels into resource

2019-06-02 17:14 UTC, ubikloadpack commented on src/protocol/http/org/apache/jmeter/protocol/http/gui/CacheManagerGui.java
> +                new JCheckBox("Use Thread Group configuration to control cache clearing", false); //$NON-NLS-1$
Externalize labels into resource

2019-06-02 17:14 UTC, ubikloadpack commented on src/protocol/http/org/apache/jmeter/protocol/http/sampler/HTTPHC4Impl.java
> +                log.info("The value of saveConnectionCookies are {}",hdr.getValue());
Why this log ? Make it more clear if needed

2019-06-02 17:14 UTC, ubikloadpack commented on src/core/org/apache/jmeter/threads/JMeterThread.java
> +    public static final ThreadLocal <Boolean>threadLocal4SameUser = new ThreadLocal<Boolean>() ;
Request was to make this field not Thread Local but a private JMeter Variable similar to the ones prefixed by __jmeter.....

2019-06-02 17:17 UTC, shaqianqian commented
Hello,
If don’t use threadlocal, how to share the value in the same thread? Thanks
for response.

UBIK LOAD PACK <notifications@github.com>于2019年6月2日 周日19:14写道：

> *@ubikloadpack* requested changes on this pull request.
> ------------------------------
>
> In test/src/org/apache/jmeter/control/TestThreadGroup.java
> <https://github.com/ubikloadpack/jmeter/pull/46#discussion_r289650283>:
>
> > +    @Before
> +    public void setup() {
> +        JMeterContextService.getContext().setVariables(new JMeterVariables());
> +        TransactionController transactionController = new TransactionController();
> +        transactionController.setGenerateParentSample(true);
> +        LoopController loop = new LoopController();
> +        loop.setLoops(1);
> +        loop.setContinueForever(false);
> +        hashTree.add(loop);
> +        hashTree.add(loop, transactionController);
> +        threadGroup.setNumThreads(1);
> +
> +    }
> +
> +    @Test
> +    public void testThreadLoaclForSameUserOnIternation() {
>
> Typo in name
> ------------------------------
>
> In src/core/org/apache/jmeter/threads/ThreadGroup.java
> <https://github.com/ubikloadpack/jmeter/pull/46#discussion_r289650290>:
>
> > @@ -69,7 +69,9 @@
>
>      /** Scheduler start delay, overrides start time */
>      public static final String DELAY = "ThreadGroup.delay";
> -
> +
> +    /** The same user or different users */
> +    public static final String ISSAMEUSER = "ThreadGroup.sameuser";
>
> Rename to IS_SAME_USER
> ------------------------------
>
> In src/core/org/apache/jmeter/threads/ThreadGroup.java
> <https://github.com/ubikloadpack/jmeter/pull/46#discussion_r289650298>:
>
> > +     * Set the kind of user
> +     *
> +     * @param isSameUser
> +     *            true is the same user
> +     *            false is the different users
> +     */
> +    public void setIsSameUser(boolean isSameUser) {
> +        setProperty(new BooleanProperty(ISSAMEUSER, isSameUser));
> +    }
> +
> +    /**
> +     * Get kind of user.
> +     *
> +     * @return the kind of user.
> +     */
> +    public boolean IsSameUser() {
>
> functions must start with lower case
> ------------------------------
>
> In src/core/org/apache/jmeter/threads/gui/ThreadGroupGui.java
> <https://github.com/ubikloadpack/jmeter/pull/46#discussion_r289650331>:
>
> > @@ -252,4 +269,17 @@ private void init() { // WARNING: called from ctor so must not be overridden (i.
>          intgrationPanel.add(mainPanel);
>          add(intgrationPanel, BorderLayout.CENTER);
>      }
> +
> +   private JPanel createUserOptionsPanel(){
> +       ButtonGroup group = new ButtonGroup();
> +       sameUserBox = new JRadioButton("Same user on each iteration"); //$NON-NLS-1$
>
> Externalize labels into resource
> ------------------------------
>
> In src/core/org/apache/jmeter/threads/gui/ThreadGroupGui.java
> <https://github.com/ubikloadpack/jmeter/pull/46#discussion_r289650335>:
>
> > @@ -252,4 +269,17 @@ private void init() { // WARNING: called from ctor so must not be overridden (i.
>          intgrationPanel.add(mainPanel);
>          add(intgrationPanel, BorderLayout.CENTER);
>      }
> +
> +   private JPanel createUserOptionsPanel(){
> +       ButtonGroup group = new ButtonGroup();
> +       sameUserBox = new JRadioButton("Same user on each iteration"); //$NON-NLS-1$
> +       group.add(sameUserBox);
> +       sameUserBox.setSelected(true);
> +       differentUserBox = new JRadioButton("Different User on Each Iteration"); //$NON-NLS-1$
>
> Externalize labels into resource
> ------------------------------
>
> In
> src/protocol/http/org/apache/jmeter/protocol/http/gui/CacheManagerGui.java
> <https://github.com/ubikloadpack/jmeter/pull/46#discussion_r289650349>:
>
> > @@ -102,12 +110,19 @@ private void init() {
>          setBorder(makeBorder());
>
>          clearEachIteration = new JCheckBox(JMeterUtils.getResString("clear_cache_per_iter"), false); // $NON-NLS-1$
> +
> +        controlledByThreadGroup =
> +                new JCheckBox("Use Thread Group configuration to control cache clearing", false); //$NON-NLS-1$
>
> Externalize labels into resource
> ------------------------------
>
> In
> src/protocol/http/org/apache/jmeter/protocol/http/sampler/HTTPHC4Impl.java
> <https://github.com/ubikloadpack/jmeter/pull/46#discussion_r289650390>:
>
> > @@ -1727,6 +1736,7 @@ private void saveConnectionCookies(HttpResponse method, URL u, CookieManager coo
>              Header[] hdrs = method.getHeaders(HTTPConstants.HEADER_SET_COOKIE);
>              for (Header hdr : hdrs) {
>                  cookieManager.addCookieFromHeader(hdr.getValue(),u);
> +                log.info("The value of saveConnectionCookies are {}",hdr.getValue());
>
> Why this log ? Make it more clear if needed
> ------------------------------
>
> In src/core/org/apache/jmeter/threads/JMeterThread.java
> <https://github.com/ubikloadpack/jmeter/pull/46#discussion_r289650458>:
>
> > @@ -238,9 +248,10 @@ private void startScheduler() {
>      public void setThreadName(String threadName) {
>          this.threadName = threadName;
>      }
> -
> +    public static final ThreadLocal <Boolean>threadLocal4SameUser = new ThreadLocal<Boolean>() ;
>
> Request was to make this field not Thread Local but a private JMeter
> Variable similar to the ones prefixed by __jmeter.....
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ubikloadpack/jmeter/pull/46?email_source=notifications&email_token=AFI7BD6W542BZRWQKKNAERDPYP5VTA5CNFSM4HRZRAS2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB2KNJEA#pullrequestreview-244634768>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFI7BDY53NKR4ICMKUKA3KLPYP5VTANCNFSM4HRZRASQ>
> .
>

2019-06-02 17:20 UTC, ubikloadpack commented
The object JMeterVariables is specific to each Thread.

2019-06-02 17:21 UTC, shaqianqian commented
Can you give me a example ?

UBIK LOAD PACK <notifications@github.com>于2019年6月2日 周日19:20写道：

> The object JMeterVariables is specific to each Thread.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ubikloadpack/jmeter/pull/46?email_source=notifications&email_token=AFI7BDZDOZ7MHLX7CRJUZXLPYP6OJA5CNFSM4HRZRAS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWX2DKY#issuecomment-498049451>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFI7BD5BM7WFTSZBFBUU56TPYP6OJANCNFSM4HRZRASQ>
> .
>

2019-06-02 17:22 UTC, ubikloadpack commented
Hi, Look at example in HTTPHC4Impl, or we'll discuss tomorrow.

2019-06-02 17:24 UTC, shaqianqian commented
Sorry I dont have laptop at home, maybe we can talk about it tomorrow,
thanks for your help

UBIK LOAD PACK <notifications@github.com>于2019年6月2日 周日19:22写道：

> Hi, Look at example in HTTPHC4Impl, or we'll discuss tomorrow.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ubikloadpack/jmeter/pull/46?email_source=notifications&email_token=AFI7BD2I5XUMNBP5ZG72LTLPYP6WTA5CNFSM4HRZRAS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWX2EWQ#issuecomment-498049626>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFI7BD35NSNJK4UJFOSTI53PYP6WTANCNFSM4HRZRASQ>
> .
>

2019-06-02 17:26 UTC, ubikloadpack commented
No problem, review was for tomorrow :-)

2019-06-07 21:03 UTC, ubikloadpack requested changes

2019-06-07 21:03 UTC, ubikloadpack commented on src/protocol/http/org/apache/jmeter/protocol/http/sampler/HTTPHC4Impl.java
> +        JMeterVariables variables = JMeterContextService.getContext().getVariables();
This should be in CacheManager#testIterationStart

2019-06-07 21:03 UTC, ubikloadpack commented on src/protocol/http/org/apache/jmeter/protocol/http/sampler/HTTPHC4Impl.java
> +            getCookieManager().setClearEachIteration(true);
This should be in CookieManager#testIterationStart

2019-06-08 10:17 UTC, ubikloadpack commented
PR is incomplete and needs rework, see mail I sent you.
Thanks

2019-06-08 10:17 UTC, closed without merging