Bug62861
ubikloadpack/jmeter pull request #48
Opened 2019-06-11 13:44 UTC by shaqianqian

## Description
modify juint test
remove a uselesse parameter

2019-06-11 14:00 UTC, ubikloadpack requested changes

2019-06-11 14:00 UTC, ubikloadpack commented on src/core/org/apache/jmeter/threads/JMeterThread.java
> -    public static final String IS_SAME_USER = "JMeterThread.is_same_user"; // $NON-NLS-1$
Why this removal ?

2019-06-11 14:00 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/sampler/TestJmeterVariableSameUser.java
>          assertTrue("When test different user on the different iternation, the cookie should be cleared",
Test is not correct, you just test variable is set and not that cookie is cleared

2019-06-11 14:00 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/sampler/TestJmeterVariableSameUser.java
>          assertFalse("When test different user on the same iternation, the cookie shouldn't be cleared",
Same as above

2019-06-11 14:00 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/sampler/TestJmeterVariableSameUser.java
> +        assertFalse("When test different user on the different iternation, the cache should be cleared",
Test is not correct, you just test variable is set and not that cache is cleared

2019-06-11 14:00 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/sampler/TestJmeterVariableSameUser.java
> +        assertTrue("When test different user on the same iternation, the cache shouldn't be cleared",
Same as above

2019-06-12 08:26 UTC, shaqianqian commented on src/core/org/apache/jmeter/threads/JMeterThread.java
> -    public static final String IS_SAME_USER = "JMeterThread.is_same_user"; // $NON-NLS-1$
Because this variable is set in JMeterVariables.java "  `static final String VAR_IS_SAME_USER_KEY = "__jmv_SAME_USER";"`

2019-06-15 10:11 UTC, ubikloadpack requested changes

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/sampler/TestHTTPHC4Impl.java
> +    private static String sameuser = "__jmv_SAME_USER";
Make it final, constants must then be upper case SAME_USER

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/sampler/TestHTTPHC4Impl.java
> +        assertTrue(hc.resetStateOnThreadGroupIteration.get());
Add a message

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +    public void testCookieManagerNotClear() throws NoSuchFieldException, IllegalAccessException {
testCookieManagerNotCleared

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +        cookieManager.setClearEachIteration(false);
Set this before cookieManager.testStarted();

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +                cookieManager.getCookies().get(0).getName());
Shouldn't you test all collection and ensure it only contains 1 item ?

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +        assertEquals("Before the iteration, the value of cookie should be what user have set", "test",
Instead of test, name it "dynamic_cookie_added_by_user"

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +        cookie1.setName("test1");
Instead of test1, name it "static_cookie"

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +    public void testCookieManagerClear() throws NoSuchFieldException, IllegalAccessException {
Try to factore code with previous method

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +    public void testCookieManagerForDifferentUser() throws NoSuchFieldException, IllegalAccessException {
testCookieManagerForDifferentUser => testCookieManagerWhenThreadIterationIsNewUser

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +    public void testCookieManagerForSameUser() throws NoSuchFieldException, IllegalAccessException {
testCookieManagerWhenThreadIterationIsSameUser

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +    public void testJmeterVariableCookieForDifferentUser() {
testJmeterVariableCookieWhenThreadIterationIsANewUser

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCookieIternation.java
> +public class TestCookieIternation {
Typo

2019-06-15 10:11 UTC, ubikloadpack commented on test/src/org/apache/jmeter/protocol/http/control/TestCacheManagerIternation.java
> +public class TestCacheManagerIternation {
Typo

2019-06-18 20:10 UTC, merged