add json2extractor
ubikloadpack/jmeter pull request #57
Opened 2019-08-01 15:24 UTC by shaqianqian

## Description
add json extractor which uses "io.burt.jmespath" 

## How Has This Been Tested?
Junit test

2019-08-01 17:01 UTC, ubikloadpack requested changes

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/JSON2Manager.java
> +public class JSON2Manager {
Rename it to JMESManager, see my comment below, this class may not be needed after doing what I request with LoadingCache

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/JSON2Manager.java
> +    public List<Object> extractWithJsonPath(String jsonString, String jsonPath) throws IOException {
It's not the correct way to do that, to ensure performances please look at Caffeine and LoadingCache and how it is used for example in JoddExtractor.

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/JSON2Manager.java
> +    public List<Object> extractWithJsonPath(String jsonString, String jsonPath) throws IOException {
jmesSelector

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/JSON2PostProcessor.java
> +public class JSON2PostProcessor extends AbstractScopedTestElement implements Serializable, PostProcessor, ThreadListener{
Call it JMESExtractor, this class looks like a copy/paste without critical review of the source. Please review this

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/JSON2PostProcessor.java
> +    private static final String JSON_PATH_EXPRESSIONS = "JSONPostProcessor.jsonPathExprs"; // $NON-NLS-1$
Rename everywhere prefix from JSONPostProcessor to JMESExtractor

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/gui/JSON2PostProcessorGui.java
> +public class JSON2PostProcessorGui extends AbstractPostProcessorGui {
Rename to JMESExtractorGui

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/gui/JSON2PostProcessorGui.java
> +        jsonPathExpressionsField.setText(config.getJsonPathExpressions());
As I said, there is only 1 expression (I don't want to reproduce what has been made in JSONPostProcessor), so it should be getJMESPathExpression(), apply this remark everywhere

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/gui/JSON2PostProcessorGui.java
> +        refNamesField.setText(config.getRefNames());
same as below note

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/gui/JSON2PostProcessorGui.java
> +        matchNumbersField.setText(config.getMatchNumbers());
same

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/gui/JSON2PostProcessorGui.java
> +        defaultValuesField.setText(config.getDefaultValues());
same

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/gui/JSON2PostProcessorGui.java
> +        computeConcatenationField.setSelected(config.getComputeConcatenation());
We won't compute Concatenation, so remove computeConcatenationField

2019-08-01 17:01 UTC, ubikloadpack commented on src/core/org/apache/jmeter/resources/messages_fr.properties
> +json2_post_processor_title=Extracteur JSON
Rename

2019-08-01 17:01 UTC, ubikloadpack commented on src/core/org/apache/jmeter/resources/messages.properties
> +json2_post_processor_title=JSON2 Extractor
Rename

2019-08-01 17:01 UTC, ubikloadpack commented on test/src/org/apache/jmeter/extractor/TestJSON2PostProcessor.java
> +public class TestJSON2PostProcessor {
Rename

2019-08-01 17:01 UTC, ubikloadpack commented on test/src/org/apache/jmeter/extractor/TestJSON2PostProcessor.java
> +    public void testProcessWith2PostProcessor2() {
Rename all methods to be more meaningful, no 2 as suffix

2019-08-01 17:01 UTC, ubikloadpack commented on test/src/org/apache/jmeter/extractor/TestJSON2PostProcessor.java
> +public class TestJSON2PostProcessor {
Take some examples from JMESPath website to have more complex ones

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/JSON2PostProcessor.java
> +                                if (getComputeConcatenation()) {
No concatenation, remove code related to it

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/JSON2PostProcessor.java
> +        String refNames = getRefNames();
We only work with one var, one jmespath  expression, one default value ....

2019-08-01 17:01 UTC, ubikloadpack commented on src/components/org/apache/jmeter/extractor/json/jsonpath/gui/JSON2PostProcessorGui.java
> +    private JLabeledTextField defaultValuesField;
Rename all fields so that it's clear they work with only 1 selector, one var ...

2019-08-02 08:15 UTC, shaqianqian commented on src/components/org/apache/jmeter/extractor/json/jsonpath/JSON2Manager.java
> +    public List<Object> extractWithJsonPath(String jsonString, String jsonPath) throws IOException {
In JoddExtractor i don't find the usage of LoadingCache and Caffeine. Can you give me more details?

2019-08-22 13:32 UTC, ubikloadpack commented
Peux-tu alimenter la documentation pour le composant ?
Voir component_reference.xml, la doc html est générée avec ant docs-site

Merci

2019-08-22 13:40 UTC, shaqianqian commented
Bonjour Philippe,
Je vais le faire toute de suite, merci.
Cordialement
Qianqian SHA

UBIK LOAD PACK <notifications@github.com>于2019年8月22日 周四15:32写道：

> Peux-tu alimenter la documentation pour le composant ?
> Voir component_reference.xml, la doc html est générée avec ant docs-site
>
> Merci
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ubikloadpack/jmeter/pull/57?email_source=notifications&email_token=AFI7BD2DYEK5DKN73BRQXCLQF2IN7A5CNFSM4IIR2RN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD45DGAI#issuecomment-523907841>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFI7BD6XTODIRPWJWDWORF3QF2IN7ANCNFSM4IIR2RNQ>
> .
>

2019-08-22 15:13 UTC, shaqianqian commented
Bonjour Philippe,
J'ai fait le document pour JMES Path, pouvez-vous m'aider de regarder?
Cordialement
Qianqian SHA

shaqianqian <sqq940814@gmail.com> 于2019年8月22日周四 下午3:40写道：

> Bonjour Philippe,
> Je vais le faire toute de suite, merci.
> Cordialement
> Qianqian SHA
>
> UBIK LOAD PACK <notifications@github.com>于2019年8月22日 周四15:32写道：
>
>> Peux-tu alimenter la documentation pour le composant ?
>> Voir component_reference.xml, la doc html est générée avec ant docs-site
>>
>> Merci
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ubikloadpack/jmeter/pull/57?email_source=notifications&email_token=AFI7BD2DYEK5DKN73BRQXCLQF2IN7A5CNFSM4IIR2RN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD45DGAI#issuecomment-523907841>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AFI7BD6XTODIRPWJWDWORF3QF2IN7ANCNFSM4IIR2RNQ>
>> .
>>
>

2019-10-14 12:17 UTC, ubikloadpack commented
Merged with some adaptations into core through:
https://github.com/apache/jmeter/pull/489

2019-10-14 12:17 UTC, closed without merging